<?php
// SPDX-License-Identifier: GPL-2.0-or-later

/**
 * @file
 * Intercepts all outgoing SMS to be rerouted to a configurable number.
 */

use AKlump\PhoneNumber\PhoneNumberFormats;
use AKlump\PhoneNumber\USPhoneNumberFormatter;
use Drupal\Core\StringTranslation\TranslatableMarkup;

/**
 * Split a string into an array by pre defined allowed delimiters.
 *
 * Items may be separated by any number and combination of:
 * spaces, commas, semicolons, or newlines.
 *
 * @param string|null $string
 *   A string to be split into an array.
 *
 * @return array
 *   An array of unique values from a string.
 */
function reroute_sms_split_string(?string $string): array {
  $numbers = [];
  if (!empty($string)) {
    $numbers = preg_split('/[\s,;\n]+/', $string ?? '', -1, PREG_SPLIT_NO_EMPTY);
  }
  $numbers = array_unique($numbers);
  $formatter = new USPhoneNumberFormatter(PhoneNumberFormats::SMS);

  return array_map(function ($number) use ($formatter) {
    if ($formatter->isValid($number)) {
      return $formatter->format($number);
    }

    return $number;
  }, $numbers);
}
